export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";

export const QUERY_REQUEST = "QUERY_REQUEST";
export const QUERY_SUCCESS = "QUERY_SUCCSSS";
export const QUERY_FAILURE = "QUERY_FAILURE";

export const QUERY_PARKING_REQUEST = "QUERY_PARKING_REQUEST";
export const QUERY_PARKING_SUCCESS = "QUERY_PARKING_SUCCESS";
export const QUERY_PARKING_FAILRUE = "QUERY_PARKING_FAILURE";