export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";

export const QUERY_REQUEST = "QUERY_REQUEST";
export const QUERY_SUCCESS = "QUERY_SUCCSSS";
export const QUERY_FAILURE = "QUERY_FAILURE";

export const QUERY_PARKING_REQUEST = "QUERY_PARKING_REQUEST";
export const QUERY_PARKING_SUCCESS = "QUERY_PARKING_SUCCESS";
export const QUERY_PARKING_FAILRUE = "QUERY_PARKING_FAILURE";

export const FORWARD_GEOCODING_REQUEST = "FORWARD_GEOCODING_REQUEST";
export const FORWARD_GEOCODING_SUCCESS = "FORWARD_GEOCODING_SUCCESS";
export const FORWARD_GEOCODING_FAILURE = "FORWARD_GEOCODING_FAILURE";

export const FETCH_LOCATION_SUGGESTIONS_REQUEST = "FETCH_LOCATION_SUGGESTIONS_REQUEST";
export const FETCH_LOCATION_SUGGESTIONS_SUCCESS = "FETCH_LOCATION_SUGGESTIONS_SUCCESS";
export const FETCH_LOCATION_SUGGESTIONS_FAILURE = "FETCH_LOCATION_SUGGESTIONS_FAILURE";
export const CLEAR_LOCATION_SUGGESTIONS = "CLEAR_LOCATION_SUGGESTIONS";

export const SET_TARGET_LOCATION = "SET_TARGET_LOCATION";
export const CLEAR_TARGET_LOCATION = "CLEAR_TARGET_LOCATION";

export const SET_PHASE = "SET_PHASE";

export const UPDATE_MAP_STATE = "UPDATE_MAP_STATE";